### ISSUE TITLE
Sticky Table Headers

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#109]
Table headers should be sticky when scrolling so the user can quickly reference the column they are looking at.

"Subheaders" (the title of an individual table) will also stick when scrolling.

**Comment by andycochran** [comment]
I've started branch `109-sticky-thead`. It has a CSS-only solution to this. It makes tables an explicit height, allowing the `tbody` to scroll while the `thead` remains still. There are a couple caveats: 1) All cells must have an explicit width, since `tbody` and `thead` are set to `display:block` to enable scrolling,  which prevents the cells auto aligning. 2) The table scrolls in addition to the page scroll, which means the `thead` doesn't have to reach the top of the layout before the `tbody` scrolls; it can scroll when it's partially below the fold. 

I've looked into Ember options for real JavaScript sticky. None of them are as full-featured as Foundation's Sticky component. It'd be rad if we could get it working here. https://gist.github.com/bravo-kernel/ed4d1e368f3ed40ecb31f72ded94376c

**Comment by andycochran** [comment]
I'd like to try adding a toggle button for the scrolling tables, so that by default they have an explicit height and you can expand them to auto height. Per #126, with the charts appearing below the tables, this would allow the charts to live slightly above the fold, so you don't have to scroll them entire table to discover them.
