### ISSUE TITLE
Update  quick facts in profile view

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#210]
Quick facts will be population, housing, and average household size

**Comment by andycochran** [comment]
@EricaMaurer Can you let us know which columns/calculations to use for these?

**Comment by EricaMaurer** [comment]
Population: Pop_1
Housing: HU1
A vg HH Size: AvgHHSz

**Comment by allthesignals** [comment]
^ That data is spread across three tables - the way the app is set up, we pull data for each profile individually. In order to show these three data points, we would need to make an additional call that pulls data across 3 tables. Can we make sure this is the approach we want to take? @chriswhong @andycochran

**Comment by andycochran** [comment]
Wouldn't it be more useful to the user to show big stats that are specific to the profile type.
