### ISSUE TITLE
Decennial Census Profile

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#213]

**Comment by chriswhong** [comment]
Need from Customer: Data & Layout Template

**Comment by allthesignals** [comment]
Todo:

Branch for 213 is pushed with an example of the sex and age table. The "config" file for this follows the same structure as ACS: find `app/table-configs/decennial`, and you will see a `sex-age` config. This may be used as a template for the others. 

In the `census.hbs` route template, you will see something slightly different:

```handlebars
{{#decennial-table category='decennial_sex_age' as |table|}}
  {{acs-table
    reliability=false
    comparison=true
    config=sexAge
    t1=table.categoryData.y2000
    t2=table.categoryData.y2010
  }}
{{/decennial-table}}
```

This is a component that sets off a data fetch task. It requires a `category` property. The value of `category` is the name of the table in Carto. The list of tables are both in the template, in the controller, and here:

```
  decennial_median_age_for_blocks_only
  decennial_dictionary
  decennial_hispanic_subgroup
  decennial_median_age_exl_blocks
  decennial_sex_age
  decennial_mutually_exclusive_race
  decennial_population_density
  decennial_asian_subgroup
  decennial_relationship_head_householder
  decennial_household_type
  decennial_housing_occupancy
  decennial_housing_tenure
  decennial_tenure_by_age
  decennial_household_size
  decennial_poppyramid_only 
```

Once rendered, the component yields its block, providing a contextual variable called `categoryData`. This behaves exactly as the others (with the exception that it does not nest the data into a 3rd tier, only into 2 tiers. We exclude category from nesting because we are calling the categories individually). 

You may need to build logic for defaulting the `significance` styling to true (since significance is not a factor).

**Comment by andycochran** [comment]
Perhaps we should change this: 
```
{{unless data.significant 'medium-gray'}}
```
to this: 
```
{{if data.insignificant 'medium-gray'}}
```
Then we won't have to do anything special for decennial.

**Comment by EricaMaurer** [comment]
Nothing will be grayed in the decennial data

**Comment by andycochran** [comment]
@EricaMaurer Yup. That's what I was trying to solve. Right now data are grayed by default in the template unless the query says they're significant. And since there's not a factor for significance in decennial, we need to reverse the logic.

**Comment by allthesignals** [comment]
Find the layout and variables here: https://docs.google.com/spreadsheets/d/1kv-qMCqjl0-pORA3r1ykUg8IzgVnVrEsZRDxfr6qAHM/edit?usp=sharing

This will highlight things and groups the exact variables into sectionns

**Comment by allthesignals** [comment]
I completed all sections... but they are unstyled. See branch for more information.
