### ISSUE TITLE
User can overlay choropleth maps to help guide the selection

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#23]

**Comment by chriswhong** [comment]
Choropleths will usually be at the NTA or PUMA level.  The approach will be to make the choropleth overlay an option when doing the "select by variable" feature.    Customer will provide guidance on styling and breaks for each choropleth.

This issue is only for the poverty filter, and can be expanded later.

**Comment by EricaMaurer** [comment]
Poverty Maps (Estimate and Percent)
Variable Label: PBwPV

Categories for Estimate Map:
50,000 or more
40,000 to 49,999
30,000 to 39,999
20,000 to 29,999
Under 20,000
 
Categories for Percent Map:
30.0 or more
25.0 to 29.9
20.0 to 24.9
15.0 to 19.9
Less than 15.0

**Comment by EricaMaurer** [comment]
Poverty Maps (Estimate and Percent)
Variable Label: PBwPV

For NTAs:
Categories for Estimate Map:
20,000 or more
15,000 to 19,999
10,000 to 14,999
5,000 to 9,999
Under 5,000

Categories for Percent Map:
50.0 or more
40.0 to 49.9
30.0 to 39.9
15.0 to 29.9
Less than 15.0

**Comment by EricaMaurer** [comment]
NTA maps only

Title for selection menu, phrasing for legend, and category breaks included in this doc

[Map Categories for PFF.xlsx](https://github.com/NYCPlanning/labs-nyc-factfinder/files/1528859/Map.Categories.for.PFF.xlsx)
