### ISSUE TITLE
Handle Single Geometry Selections Differently

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#254]
When the user has a single geometry selected, the data used in the reports should be whatever is in the raw data, and should not use the same SQL as an aggregation of geometries.

**Comment by allthesignals** [comment]
Alright - I think this is related to another issue. Could we clarify a little more? I don't understand the need for this yet - if only one geometry is selected, it won't matter than an aggregation function is being applied. @chriswhong @EricaMaurer

**Comment by EricaMaurer** [comment]
If a single ct, puma, boro, city is selected the data should pull straight from our database rather than calculated. Things may be different than what comes from the census bureau if calculated (they have more granular data available for calculations than we do) and we don't want to destroy their data by calculating our own if we have it available

**Comment by allthesignals** [comment]
Spot check of a single CT:
![image](https://user-images.githubusercontent.com/5004319/33688701-54328a9e-daaa-11e7-9991-54a5836af531.png)
![image](https://user-images.githubusercontent.com/5004319/33688706-572ac46e-daaa-11e7-88db-6efbfc3e0ea9.png)

@EricaMaurer, unless there are some test cases where single-geometry profiles do not match what is directly in the database, I don't think there's a real issue here. Thanks!

**Comment by allthesignals** [comment]
@EricaMaurer:
> Percent moe is being calculated when it's in the database as blank.. And a separate issue that's recorded is for the special vases where cells are blank

**Comment by allthesignals** [comment]
We need to build this logic into the SQL query:

When using a single geometry, do not aggregate the MOE. In the above example, `z` is simply `null`, which should be the result. Not clear how 15.6 is the result.
