### ISSUE TITLE
User can  select comparison area from a list of pre-defined sub-boro geographies (NYC, Boros, PUMAs, NTAs)

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#27]
only in "standard" and "change comparison" report view (without reliability)

**Comment by chriswhong** [comment]
- Make table header that currently reads "Comparison Area" into an input that triggers the update.
- Idea: typeahead, or indented list

**Comment by allthesignals** [comment]
@andycochran where should the dropdown select go?

**Comment by andycochran** [comment]
Hmm… Since it'll control the comparisons in multiple tables, it doesn't make sense to put it in the table header as mentioned before. And it shouldn't appear to be associated with any one particular table. 

I suppose the place for it is in the report header, maybe below the map. It makes sense to me to control your comparison area right there where your selection is shown. Let's put it there, at least for now. 

If it's in the same `.cell` as the map, the map's heigh will need to be adjusted. It's `height:100%;` now, and will need to be `height: calc(100% - [height of select]);` of the button will cause the cell to scroll.

**Comment by allthesignals** [comment]
@andycochran Alright. I was hoping to see a solid decision and mockup for things like this. I will put it below the map, but it's important that I ask because it could affect how I should set up the query parameters and the way they delegate changes to child routes. 

Below the map means: the query param exists for each route, possibly with a different name. If we want it in the top level (where the tabs are), it's a different approach. So I hope this is closest to what we end up deciding on.

**Comment by andycochran** [comment]
Ooh. If it's difficult to mov around, I can mock it up.
