### ISSUE TITLE
User can select tracts and blocks by various pre-defined geometries

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#41]

**Comment by chriswhong** [comment]
- Citywide
- Borough
- PUMAs/CD 
- NTA

**Comment by chriswhong** [comment]
Discussions led to thinking of any aggregated geometries as "selection tools" just like a polygon or circle tool... you must "start" and "end" the use of the tool, which results in a chunk of atomic geometries being added to the selection.

When no tool is selected, users can still click on individual atomic units to toggle their selected status.  

Census tracts are big enough that they can be shown and interacted with at citywide zoom levels.

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/32012558-3dcee2f6-b986-11e7-8bad-16e8e023a97f.png)

**Comment by andycochran** [comment]
When some number of tracts are selected: 

![image](https://user-images.githubusercontent.com/409279/32015758-07d055b8-b990-11e7-9b18-18fb6f98f4a4.png)

**Comment by andycochran** [comment]
NTA selection (same pattern for PUMA & Borough):

![image](https://user-images.githubusercontent.com/409279/32019726-1841513e-b99c-11e7-8c31-54d4d92bea88.png)

**Comment by allthesignals** [comment]
@andycochran in Default app state (with sample tooltip), how does one return to the default view after pressing one of the utilities (polygon, point, etc)?

**Comment by andycochran** [comment]
Hmm? "Default app state" is the "default view." I just labeled the mockups above A, B, and C. Let's see if I can explain… 

From A or B, if you click one of selection tools, you go to C. From C, the "add to selection" button will return you to B (with a selection). 

I suppose the question is: 
From C, if you don't choose any geographies, how do you return to A/B ? 

Possible solution: 
On C, if you don't choose any geographies, you see a "cancel / return to selection" button instead of the "add to selection" button.

**Comment by andycochran** [comment]
After chatting with the customer, these mockup are not going to work. Our assumption that NTAs and PUMAs could be "selection tools" (just like polygon, circle) is incorrect. The data will contain rows for NTAs and PUMAs. These rows should power the report view, instead of us aggregating collections of tracts on-the-fly. 

The user needs to be able to: 
- Create a selection by block, tract, NTA, or PUMA
- Use the point and polygon selection tools or clicking to edit their selection

**Comment by andycochran** [comment]
### New mockup with all four selector types (draw tools kept separate): 

![image](https://user-images.githubusercontent.com/409279/32074226-bbc65708-ba66-11e7-8546-649bdd59df11.png)

As @CeciliaCY points out, there's probably a better place for the clear button (closer to the selection count, but not too close to other buttons as to be accidentally clicked). We'll iterate on this as we introduce new features.
