### ISSUE TITLE
Compare to list: Rearrange PUMA list order

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#463]
This was done already but should be rearranged to have an order

**Comment by EricaMaurer** [comment]
[CompareToList_PUMAs.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cb9b97338391acbbe6934ab749cfa41c6b06606b48e13b628ae92dbc56395b4d5a47f9490c5d40adfb8123f2e238708a5a5fe8d5695f70cf2f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e68d884e3718011d8efe5427ed.xlsx)

**Comment by andycochran** [comment]
As this list is generated from a SQL query, is there a property by which we can order them? GeoID? 

Putting them into the specific order provided and grouping them by boro would require config and 5 separate sub queries. 

However, I'm not sure this order is necessary. The purpose of the `ember-power-select-search-input` component is to allow the user to easily find what they're looking for just by typing instead of scrolling through the list.

**Comment by allthesignals** [comment]
Agree. Just alphabetize and let people search. Custom ordering requires its own dataset

**Comment by allthesignals** [comment]
That component addon might have a sort option. If it’s a computed it’s easy to sort with array methods (sortBy)
