### ISSUE TITLE
single geog: percentage point difference not all always graying

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#545]
https://nyc-factfinder.planninglabs.nyc/profile/735/social?charts=false&comparator=SI07&reliability=true
![image](https://user-images.githubusercontent.com/32674674/36445187-813fb41c-164b-11e8-9ed9-f8dd269e267e.png)

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-05 at 10.36.09 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f66b7191a379ef0c2857415f47bc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e14f53a0123e6ae47e336e0a.png)Possibly related to #548

**Comment by allthesignals** [comment]
So this is related to percentage point difference significance, but your PR added code for the significance calculation which is different. Gonna look at the SQL and create a test

**Comment by EricaMaurer** [comment]
Ok cool. #528 was for change, this issue is difference

**Comment by allthesignals** [comment]
I think I meant this PR https://github.com/NYCPlanning/labs-factfinder-api/pull/31/files

**Comment by allthesignals** [comment]
What are the inputs for this significance calculations? Trying to double check formulas.

**Comment by EricaMaurer** [comment]
percentage point est and MOE

**Comment by EricaMaurer** [comment]
#31 was for special variables

**Comment by allthesignals** [comment]
Alright, I have a failing test for this.


The math for this is as follows:

```sql
WHEN ABS(
  SQRT(
    POWER(coalesce(percent_m, 0) / 1.645, 2) 
      + POWER(coalesce(comparison_percent_m, 0) / 1.645, 2)
  ) * 1.645 ) > ABS(comparison_percent - percent)
THEN 
  false
ELSE true
```

I think what's happening is that comparison_person is null, so it can't perform math on an unknown value. That pollutes the entire calculation because it can't do boolean logic on a null value.

This is a tricky thing in some languages - JavaScript is fast and loose with nulls and embraces the "truthiness" concept where `null` is considered "falsey" and therefore evaluatable in boolean logic. 

In our SQL script this seems like a bigger issue of how to deal with nulls and 0s mid-calculation - sometimes we should assume null is 0 for additional calculations mid-stream, but those values shouldn't be null when they are served out to the app.

PR incoming.
